//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changa.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Changa.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you satisfied with the job?.
        /// </summary>
        internal static string Are_you_satisfied_with_the_job {
            get {
                return ResourceManager.GetString("Are_you_satisfied_with_the_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you satisfied with the work?.
        /// </summary>
        internal static string Are_you_satisfied_with_the_work {
            get {
                return ResourceManager.GetString("Are_you_satisfied_with_the_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to assign?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_assign {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to complete?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_complete {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to log out?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_log_out {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASSIGNED TO:.
        /// </summary>
        internal static string ASSIGNED_TO {
            get {
                return ResourceManager.GetString("ASSIGNED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bid.
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BY:.
        /// </summary>
        internal static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificate.
        /// </summary>
        internal static string Calificate {
            get {
                return ResourceManager.GetString("Calificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations you have a new job!.
        /// </summary>
        internal static string Congratulations_you_have_a_new_job {
            get {
                return ResourceManager.GetString("Congratulations_you_have_a_new_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to process.
        /// </summary>
        internal static string Failed_to_process {
            get {
                return ResourceManager.GetString("Failed_to_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has been completed.
        /// </summary>
        internal static string Has_been_completed {
            get {
                return ResourceManager.GetString("Has_been_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I failed to login.
        /// </summary>
        internal static string I_failed_to_login {
            get {
                return ResourceManager.GetString("I_failed_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login with Google.
        /// </summary>
        internal static string Login_with_Google {
            get {
                return ResourceManager.GetString("Login_with_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My page.
        /// </summary>
        internal static string My_page {
            get {
                return ResourceManager.GetString("My_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New proposals for your work!.
        /// </summary>
        internal static string New_proposals_for_your_work {
            get {
                return ResourceManager.GetString("New_proposals_for_your_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notices.
        /// </summary>
        internal static string Notices {
            get {
                return ResourceManager.GetString("Notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please complete your phone number.
        /// </summary>
        internal static string Please_complete_your_phone_number {
            get {
                return ResourceManager.GetString("Please_complete_your_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post failed.
        /// </summary>
        internal static string Post_failed {
            get {
                return ResourceManager.GetString("Post_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post has been completed.
        /// </summary>
        internal static string Post_has_been_completed {
            get {
                return ResourceManager.GetString("Post_has_been_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postal Code.
        /// </summary>
        internal static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process is complete.
        /// </summary>
        internal static string Process_is_complete {
            get {
                return ResourceManager.GetString("Process_is_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proposal.
        /// </summary>
        internal static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UnBid.
        /// </summary>
        internal static string UnBid {
            get {
                return ResourceManager.GetString("UnBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workers.
        /// </summary>
        internal static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Works.
        /// </summary>
        internal static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
